// This file is autogenerated. Changes will be overwritten.
#include "SVODSI3R2M/moc_getlyrics.cpp"
#include "SVODSI3R2M/moc_lyricsmodel.cpp"
#include "SVODSI3R2M/moc_nodemanager.cpp"
#include "SVODSI3R2M/moc_search.cpp"
#include "SVODSI3R2M/moc_searchmodel.cpp"
